//! Emit `migration-report.md` at the workspace root.

use std::fs;
use std::path::Path;

use orbit_common::types::OrbitError;

use super::MigrationReport;

pub(super) fn write_report(path: &Path, report: &MigrationReport) -> Result<(), OrbitError> {
    let mut out = String::new();
    out.push_str("# ADR migration report\n\n");
    out.push_str(
        "Generated by `orbit adr migrate`. This file is one-shot output; do not commit it.\n\n",
    );
    out.push_str(&format!(
        "- Created: {}\n- Skipped (idempotent): {}\n- Validation warnings: {}\n- Rollups: {}\n- References rewritten: {}\n- References unresolved: {}\n- Supersession edges written: {}\n\n",
        report.created.len(),
        report.skipped.len(),
        report.validation_warnings.len(),
        report.rollups.len(),
        report.rewrites.len(),
        report.unresolved_references.len(),
        report.supersedes.len(),
    ));

    out.push_str("## Validation warnings\n\n");
    if report.validation_warnings.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        out.push_str("| Legacy ID | Global ID | Warnings |\n");
        out.push_str("|-----------|-----------|----------|\n");
        for record in &report.validation_warnings {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                record.legacy_id,
                record.global_id,
                record.warnings.join("; "),
            ));
        }
        out.push('\n');
    }

    out.push_str("## Unresolved references\n\n");
    if report.unresolved_references.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        out.push_str("| File | Line | Original | Reason |\n");
        out.push_str("|------|------|----------|--------|\n");
        for record in &report.unresolved_references {
            out.push_str(&format!(
                "| `{}` | {} | `{}` | {} |\n",
                record.file.display(),
                record.line,
                record.original.replace('|', "\\|"),
                record.reason,
            ));
        }
        out.push('\n');
    }

    out.push_str("## Rollups\n\n");
    if report.rollups.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        out.push_str("| Global ID | Rollup source | Folded source paths |\n");
        out.push_str("|-----------|---------------|---------------------|\n");
        for record in &report.rollups {
            out.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                record.global_id,
                record.rollup_legacy_id,
                record.folded_legacy_ids.join(", "),
            ));
        }
        out.push('\n');
    }

    out.push_str("## Supersession edges\n\n");
    if report.supersedes.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        out.push_str("| Old | New | Source |\n");
        out.push_str("|-----|-----|--------|\n");
        for record in &report.supersedes {
            out.push_str(&format!(
                "| `{}` | `{}` | `{}` |\n",
                record.old_global_id,
                record.new_global_id,
                record.source_path.display(),
            ));
        }
        out.push('\n');
    }

    fs::write(path, out).map_err(|e| OrbitError::Io(format!("write {}: {e}", path.display())))
}
