root = "~/.orbit"

[execution.env]
inherit = false
pass = ["HOME","PATH","CODEX_HOME"]

[task.approval]
required_for_agent = true
delegate_approval = true

# ----------------------------------
# Backend Instances
# ----------------------------------

[job]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "jobs", format = "yaml"}

[activity]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "activities", format = "yaml" }

[skill]
# only markdown is supported for now (default = file)
persistence = { type = "file", path = "skills", format = "md" }

[task]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "tasks", format = "yaml" }

[audit]
# only sqlite is supported for now (default = sqlite)
persistence = { type = "sqlite", path = "orbit.db" }
