[execution.env]
inherit = false
pass = ["HOME","PATH","CODEX_HOME"]

[task.approval]
required_for_agent = true
delegate_approval = true

# ----------------------------------
# Backend Instances
# ----------------------------------

[scheduler]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "~/.orbit/schedulers/", format = "yaml"}

[job]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "~/.orbit/jobs/", format = "yaml" }

[skill]
# only markdown is supported for now (default = file)
persistence = { type = "file", path = "~/.orbit/skills/", format = "md" }

[task]
# yaml + sqlite are supported for now (default = file)
persistence = { type = "file", path = "~/.orbit/tasks/", format = "yaml" }

[watch]
# only sqlite is supported for now (default = sqlite)
persistence = { type = "sqlite", path = "~/.orbit/orbit.db"}

[audit]
# only sqlite is supported for now (default = sqlite)
persistence = { type = "sqlite", path = "~/.orbit/orbit.db" }
